[2025-08-03T06:45:47.459+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-03T06:45:47.487+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cleanup_paused_dags.delete_paused_dags manual__2025-08-03T06:45:47.267663+00:00 [queued]>
[2025-08-03T06:45:47.494+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cleanup_paused_dags.delete_paused_dags manual__2025-08-03T06:45:47.267663+00:00 [queued]>
[2025-08-03T06:45:47.494+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-03T06:45:47.506+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): delete_paused_dags> on 2025-08-03 06:45:47.267663+00:00
[2025-08-03T06:45:47.515+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=512) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-03T06:45:47.516+0000] {standard_task_runner.py:63} INFO - Started process 513 to run task
[2025-08-03T06:45:47.516+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'cleanup_paused_dags', 'delete_paused_dags', 'manual__2025-08-03T06:45:47.267663+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/cleanup_paused_dags.py', '--cfg-path', '/tmp/tmpkz3eox87']
[2025-08-03T06:45:47.517+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask delete_paused_dags
[2025-08-03T06:45:47.563+0000] {task_command.py:426} INFO - Running <TaskInstance: cleanup_paused_dags.delete_paused_dags manual__2025-08-03T06:45:47.267663+00:00 [running]> on host 19828dfd2b76
[2025-08-03T06:45:47.644+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='cleanup_paused_dags' AIRFLOW_CTX_TASK_ID='delete_paused_dags' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T06:45:47.267663+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-03T06:45:47.267663+00:00'
[2025-08-03T06:45:47.645+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-03T06:45:47.664+0000] {cleanup_paused_dags.py:48} INFO - 找到 1 個暫停的 DAG
[2025-08-03T06:45:50.117+0000] {cleanup_paused_dags.py:65} INFO - ✅ 成功刪除 DAG: dag_bbbbbbb
[2025-08-03T06:45:50.117+0000] {cleanup_paused_dags.py:74} INFO - 完成！成功刪除 1 個暫停的 DAG
[2025-08-03T06:45:50.118+0000] {python.py:237} INFO - Done. Returned value was: 完成！成功刪除 1 個暫停的 DAG
[2025-08-03T06:45:50.118+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-03T06:45:50.146+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=cleanup_paused_dags, task_id=delete_paused_dags, run_id=manual__2025-08-03T06:45:47.267663+00:00, execution_date=20250803T064547, start_date=20250803T064547, end_date=20250803T064550
[2025-08-03T06:45:50.177+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-03T06:45:50.213+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-03T06:45:50.216+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
