[2025-08-03T11:27:01.201+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-03T11:27:01.220+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cleanup_paused_dags.delete_paused_dags_with_api scheduled__2025-08-03T11:26:00+00:00 [queued]>
[2025-08-03T11:27:01.225+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cleanup_paused_dags.delete_paused_dags_with_api scheduled__2025-08-03T11:26:00+00:00 [queued]>
[2025-08-03T11:27:01.225+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-03T11:27:01.234+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): delete_paused_dags_with_api> on 2025-08-03 11:26:00+00:00
[2025-08-03T11:27:01.239+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5096) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-03T11:27:01.239+0000] {standard_task_runner.py:63} INFO - Started process 5097 to run task
[2025-08-03T11:27:01.240+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'cleanup_paused_dags', 'delete_paused_dags_with_api', 'scheduled__2025-08-03T11:26:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/cleanup_paused_dags.py', '--cfg-path', '/tmp/tmpkwyj4qlg']
[2025-08-03T11:27:01.241+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask delete_paused_dags_with_api
[2025-08-03T11:27:01.309+0000] {task_command.py:426} INFO - Running <TaskInstance: cleanup_paused_dags.delete_paused_dags_with_api scheduled__2025-08-03T11:26:00+00:00 [running]> on host cdda54659481
[2025-08-03T11:27:01.395+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='cleanup_paused_dags' AIRFLOW_CTX_TASK_ID='delete_paused_dags_with_api' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T11:26:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T11:26:00+00:00'
[2025-08-03T11:27:01.396+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-03T11:27:01.416+0000] {cleanup_paused_dags.py:86} INFO - 找到 2 個暫停的 DAG
[2025-08-03T11:27:04.413+0000] {cleanup_paused_dags.py:104} INFO - 成功刪除 Airflow DAG: dag_55555
[2025-08-03T11:27:04.429+0000] {cleanup_paused_dags.py:50} INFO - 成功調用 API 刪除 DAG 資料: dag_55555
[2025-08-03T11:27:06.734+0000] {cleanup_paused_dags.py:104} INFO - 成功刪除 Airflow DAG: dag_556666
[2025-08-03T11:27:06.746+0000] {cleanup_paused_dags.py:50} INFO - 成功調用 API 刪除 DAG 資料: dag_556666
[2025-08-03T11:27:06.747+0000] {cleanup_paused_dags.py:126} INFO - 完成！成功刪除 2 個 Airflow DAG，API 成功刪除 2 個資料庫記錄
[2025-08-03T11:27:06.748+0000] {python.py:237} INFO - Done. Returned value was: 完成！成功刪除 2 個 Airflow DAG，API 成功刪除 2 個資料庫記錄
[2025-08-03T11:27:06.749+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-03T11:27:06.810+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=cleanup_paused_dags, task_id=delete_paused_dags_with_api, run_id=scheduled__2025-08-03T11:26:00+00:00, execution_date=20250803T112600, start_date=20250803T112701, end_date=20250803T112706
[2025-08-03T11:27:06.865+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-03T11:27:06.886+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-03T11:27:06.889+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
