[2025-08-03T10:40:01.437+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-03T10:40:01.464+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cleanup_dag_logs.clean_old_logs scheduled__2025-08-02T00:00:00+00:00 [queued]>
[2025-08-03T10:40:01.472+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cleanup_dag_logs.clean_old_logs scheduled__2025-08-02T00:00:00+00:00 [queued]>
[2025-08-03T10:40:01.473+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-03T10:40:01.487+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): clean_old_logs> on 2025-08-02 00:00:00+00:00
[2025-08-03T10:40:01.494+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1239) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-03T10:40:01.495+0000] {standard_task_runner.py:63} INFO - Started process 1240 to run task
[2025-08-03T10:40:01.494+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'cleanup_dag_logs', 'clean_old_logs', 'scheduled__2025-08-02T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/cleanup_logs.py', '--cfg-path', '/tmp/tmpr833559e']
[2025-08-03T10:40:01.496+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask clean_old_logs
[2025-08-03T10:40:01.554+0000] {task_command.py:426} INFO - Running <TaskInstance: cleanup_dag_logs.clean_old_logs scheduled__2025-08-02T00:00:00+00:00 [running]> on host cdda54659481
[2025-08-03T10:40:01.632+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cleanup_dag_logs' AIRFLOW_CTX_TASK_ID='clean_old_logs' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-02T00:00:00+00:00'
[2025-08-03T10:40:01.632+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-03T10:40:01.650+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-03T10:40:01.651+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-03T10:40:01.657+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=cleanup_dag_logs, task_id=clean_old_logs, run_id=scheduled__2025-08-02T00:00:00+00:00, execution_date=20250802T000000, start_date=20250803T104001, end_date=20250803T104001
[2025-08-03T10:40:01.668+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-03T10:40:01.681+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-03T10:40:01.683+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
