[2025-08-05T05:08:34.941+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-05T05:08:34.989+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cleanup_dag_logs.clean_old_logs scheduled__2025-08-04T00:00:00+00:00 [queued]>
[2025-08-05T05:08:34.999+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cleanup_dag_logs.clean_old_logs scheduled__2025-08-04T00:00:00+00:00 [queued]>
[2025-08-05T05:08:34.999+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-05T05:08:35.014+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): clean_old_logs> on 2025-08-04 00:00:00+00:00
[2025-08-05T05:08:35.021+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=183) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-05T05:08:35.022+0000] {standard_task_runner.py:63} INFO - Started process 197 to run task
[2025-08-05T05:08:35.021+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'cleanup_dag_logs', 'clean_old_logs', 'scheduled__2025-08-04T00:00:00+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/cleanup_logs.py', '--cfg-path', '/tmp/tmpj7_owsid']
[2025-08-05T05:08:35.022+0000] {standard_task_runner.py:91} INFO - Job 219: Subtask clean_old_logs
[2025-08-05T05:08:35.060+0000] {task_command.py:426} INFO - Running <TaskInstance: cleanup_dag_logs.clean_old_logs scheduled__2025-08-04T00:00:00+00:00 [running]> on host 8032ab58e64f
[2025-08-05T05:08:35.132+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cleanup_dag_logs' AIRFLOW_CTX_TASK_ID='clean_old_logs' AIRFLOW_CTX_EXECUTION_DATE='2025-08-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-04T00:00:00+00:00'
[2025-08-05T05:08:35.133+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-05T05:08:35.276+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-05T05:08:35.276+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-05T05:08:35.283+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=cleanup_dag_logs, task_id=clean_old_logs, run_id=scheduled__2025-08-04T00:00:00+00:00, execution_date=20250804T000000, start_date=20250805T050834, end_date=20250805T050835
[2025-08-05T05:08:35.316+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-05T05:08:35.328+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-05T05:08:35.330+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
